import { useGLTF } from "@react-three/drei";
import React, { useRef } from 'react';


export function Model(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('./mbp14.glb')
    return (
        // <Center>
        <group ref={group} {...props} dispose={null}>
            <group rotation={[90, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.CpRxqsFibJhVZKA.geometry}
                    material={materials.CGiumILqqSMVyeb}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.pPCeNYAcgHQGnfB.geometry}
                    material={materials.jRMWtdSAaujlvUA}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.WeTEPJkcTkMBwBo.geometry}
                    material={nodes.WeTEPJkcTkMBwBo.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.yxTDdMZViYkuOKm.geometry}
                    material={materials.BczvixNfkWQzRzZ}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.aUVveCqqwsqchVB.geometry}
                    material={nodes.aUVveCqqwsqchVB.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.CEvArJuvvmtQsgk.geometry}
                    material={nodes.CEvArJuvvmtQsgk.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.CYSMUQxZlNCBYTF.geometry}
                    material={nodes.CYSMUQxZlNCBYTF.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ehiyYGFzDbgxhiD.geometry}
                    material={nodes.ehiyYGFzDbgxhiD.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ESbzqoApOvgbqCM.geometry}
                    material={nodes.ESbzqoApOvgbqCM.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.fiqlelggeOoTUAw.geometry}
                    material={materials.SELuppcPLrlTpBi}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.FnbkdmFKVeCCxTX.geometry}
                    material={materials.ZpTrUizuxJQUyzW}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.jiJDsRkXsnjVzCd.geometry}
                    material={nodes.jiJDsRkXsnjVzCd.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.JtnJKXAEPaOoepM.geometry}
                    material={nodes.JtnJKXAEPaOoepM.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.NhThIZELXlNUoIr.geometry}
                    material={nodes.NhThIZELXlNUoIr.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.PbJkUSFBOfThIZE.geometry}
                    material={nodes.PbJkUSFBOfThIZE.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.RYgQzNzcnFbacQH.geometry}
                    material={nodes.RYgQzNzcnFbacQH.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.YvEVHGlTGUxXlGj.geometry}
                    material={nodes.YvEVHGlTGUxXlGj.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.zlRXoydEgBQgFUa.geometry}
                    material={materials['screen backframe']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.abgVijaHVNRUvcc.geometry}
                    material={materials.screen}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.aqQHZmtSqmOcJrJ.geometry}
                    material={nodes.aqQHZmtSqmOcJrJ.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.bYMJoztGEkchzEz.geometry}
                    material={nodes.bYMJoztGEkchzEz.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.DAuseNOrQKyrxKl.geometry}
                    material={nodes.DAuseNOrQKyrxKl.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.eAcvqfZlEdoxHsj.geometry}
                    material={materials.IlNnjEDxsExlBOr}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.EwUiiUDZLcXMPFf.geometry}
                    material={nodes.EwUiiUDZLcXMPFf.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.fERhErXVTNqvOgR.geometry}
                    material={nodes.fERhErXVTNqvOgR.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.gkxaPoMYYRpyVMR.geometry}
                    material={materials.iPZiEncThgnBMJv}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.guoofBSjCEiTIJr.geometry}
                    material={nodes.guoofBSjCEiTIJr.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.jvyJQHpRnZNPEYh.geometry}
                    material={nodes.jvyJQHpRnZNPEYh.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.KCEhahuknsxQOxv.geometry}
                    material={materials.HpEeGHRuOqfcIZU}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.KJGApIEIPKlDIsA.geometry}
                    material={nodes.KJGApIEIPKlDIsA.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.kTgHOsocTlVqVAv.geometry}
                    material={nodes.kTgHOsocTlVqVAv.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.MrXuKTffTmUoNPF.geometry}
                    material={nodes.MrXuKTffTmUoNPF.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mUrIWHenIQKVHcb.geometry}
                    material={nodes.mUrIWHenIQKVHcb.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.MwHxcVTumDWogJY.geometry}
                    material={nodes.MwHxcVTumDWogJY.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.NdRhLFCrSxRNTxn.geometry}
                    material={nodes.NdRhLFCrSxRNTxn.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.NgmQYtxXWDmCavo.geometry}
                    material={nodes.NgmQYtxXWDmCavo.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.NqLxSKdAypgOdPC.geometry}
                    material={nodes.NqLxSKdAypgOdPC.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.NWErafhynAfYQEz.geometry}
                    material={materials.trackpad}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.piXptsgcOfaGWrM.geometry}
                    material={materials.WLATjirhQCUYAAG}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.PSIiVLWbMOjTmDb.geometry}
                    material={nodes.PSIiVLWbMOjTmDb.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.PTxrSKzcEmHVtif.geometry}
                    material={nodes.PTxrSKzcEmHVtif.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.QFFLzaWPRnuQYJR.geometry}
                    material={nodes.QFFLzaWPRnuQYJR.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.QHqPxKdexBoFnAK.geometry}
                    material={materials.zaEqorbaeeADKgU}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.QMBrsnrwfcVKELm.geometry}
                    material={nodes.QMBrsnrwfcVKELm.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.QYMcPaZnXQfyXcJ.geometry}
                    material={materials.NQXltfOcKPZPQdI}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rfvvXsEFOKaGwyn.geometry}
                    material={nodes.rfvvXsEFOKaGwyn.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.RgJfwZBuZcVWHTq.geometry}
                    material={nodes.RgJfwZBuZcVWHTq.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rIsAbujsARaHSub.geometry}
                    material={nodes.rIsAbujsARaHSub.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.RjGOdbHqvxkiDns.geometry}
                    material={nodes.RjGOdbHqvxkiDns.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.RkSurqpnfNMQZfv.geometry}
                    material={nodes.RkSurqpnfNMQZfv.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SjSNuZdtWKZRuoq.geometry}
                    material={nodes.SjSNuZdtWKZRuoq.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SjXIFRJFXEqYDUr.geometry}
                    material={nodes.SjXIFRJFXEqYDUr.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.TCGsaoyNbPKzeSS.geometry}
                    material={nodes.TCGsaoyNbPKzeSS.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.tEHnKyDsqJuxIpz.geometry}
                    material={nodes.tEHnKyDsqJuxIpz.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.tEwRkclpxjXZzil.geometry}
                    material={materials.UPMcPXFSRXevSGt}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.UxiDBlCRfXiMBzT.geometry}
                    material={nodes.UxiDBlCRfXiMBzT.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.vivXPkdlqllUnrl.geometry}
                    material={nodes.vivXPkdlqllUnrl.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.VqfccLWHjnpnmIO.geometry}
                    material={nodes.VqfccLWHjnpnmIO.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.vzKzmJaaFXHtgRf.geometry}
                    material={nodes.vzKzmJaaFXHtgRf.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.WPFmzKypKbUYgQT.geometry}
                    material={nodes.WPFmzKypKbUYgQT.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.wXiLpiodZWNDroe.geometry}
                    material={materials.HPAOpCInJKBtaOC}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.xjTvBwZFGvSMOud.geometry}
                    material={nodes.xjTvBwZFGvSMOud.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.xlRLalLTesirCGW.geometry}
                    material={nodes.xlRLalLTesirCGW.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.YJMoQnvBNpTrgeH.geometry}
                    material={nodes.YJMoQnvBNpTrgeH.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ZlizOzukFeXwbga.geometry}
                    material={materials.kOcboIDeohDRqCf}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rQNJSUqpGWbPRJz.geometry}
                    material={nodes.rQNJSUqpGWbPRJz.material}
                />
            </group>
        </group>
        // </Center>
    )
}

useGLTF.preload('./darkmacbook.glb')
